project_id = "sqndyvrpcjlymxqynaav"

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.validate-scan-limit]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
